### ISSUE TITLE
Connect with heroku

### ISSUE THREAD

**Issue by johnmara** [playframework/play-mailer#102]
Hello, I'm using Play Framework 2.5 and I've deployed my app on Heroku.
The problem is that the same configuration  that works locally, is not working on heroku. 
Specifically my application.conf file contains:
```
play.mailer {
  host=smtp.gmail.com
  port=465
  ssl=yes
  user="sendermail@sth.sth"
  password=mypassword
}
```
And my method which sends the email contains:
```
    public Result madebyme(){
        Email email = new Email();
        email.setSubject("Welcome to my app");
        email.setFrom("My app<sendermail@sth.sth");
        email.addTo("<receivermail@sth.sth>");
        email.setBodyText("A text message");
        mailerClient.send(email);
        return ok();
    }
```
When sending from heroku I get the error:

```
2016-06-28T11:21:18.201681+00:00 app[web.1]: [error] application - 
2016-06-28T11:21:18.201715+00:00 app[web.1]: 	at play.api.libs.mailer.MailerClient$class.send(MailerPlugin.scala:56)
2016-06-28T11:21:18.201729+00:00 app[web.1]: 	at javax.mail.Transport.send(Transport.java:124)
2016-06-28T11:21:44.765639+00:00 app[web.1]: 	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
2016-06-28T11:21:44.765646+00:00 app[web.1]: 	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1421)
2016-06-28T11:21:44.765649+00:00 app[web.1]: 	at play.api.libs.mailer.SMTPDynamicMailer.send(MailerPlugin.scala:117)
2016-06-28T11:21:44.765650+00:00 app[web.1]: 	at play.api.libs.mailer.MailerClient$class.send(MailerPlugin.scala:56)
2016-06-28T11:21:44.765657+00:00 app[web.1]: 534-5.7.14  Learn more at
2016-06-28T11:21:44.765658+00:00 app[web.1]: 534 5.7.14  https://support.google.com/mail/answer/78754 bh4sm4680997wjc.43 - gsmtp
2016-06-28T11:21:44.765671+00:00 app[web.1]: 	at org.apache.commons.mail.Email.send(Email.java:1448)
2016-06-28T11:22:04.966121+00:00 app[web.1]: 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
2016-06-28T11:22:04.966125+00:00 app[web.1]: 	at play.api.libs.mailer.SMTPDynamicMailer.send(MailerPlugin.scala:117)
2016-06-28T11:22:04.966130+00:00 app[web.1]: 534-5.7.14 L7wRi827TVVn-_78HytiH4cAeTHWOYrvc1vdWF_7br_gcNB0JZDAEkfLZ8bpRu5ZqnhAjJ
2016-06-28T11:22:04.966131+00:00 app[web.1]: 534-5.7.14 oDf-9Fo-BDj3WOQqLkDd1L__bsSC72n-XzMKMIMS5cNHcNggAzZCWir6F6eu_2G4ChQopr
2016-06-28T11:22:04.966135+00:00 app[web.1]: 	at com.sun.mail.smtp.SMTPTransport$Authenticator.authenticate(SMTPTransport.java:892)
2016-06-28T11:22:04.966140+00:00 app[web.1]: 	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1411)
2016-06-28T11:22:04.966141+00:00 app[web.1]: 	at org.apache.commons.mail.Email.send(Email.java:1448)
```

**Comment by Mogztter** [comment]
Hello @johnmara I think you need to enable "less secure apps" on your Gmail account: https://www.google.com/settings/security/lesssecureapps

There's an open issue to be able to use a more secure authentication mechanism #97

**Comment by Mogztter** [comment]
You should also follow this guide to understand why the authorization failed: https://support.google.com/accounts/answer/6009563

In your case, you are trying to authenticate from a new location (Heroku).

**Comment by Mogztter** [comment]
@johnmara Is it working now ? Can I close this issue ?

**Comment by johnmara** [comment]
Finally I used sendgrid and worked without a problem.

**Comment by Mogztter** [comment]
Ok so this is definitely related to a configuration issue with Gmail.
I'm closing this issue :smile:

**Comment by Gex8** [comment]
You have to check two important things when you want to send emails via Gmail smtp:

1. Your apps configuration:
- host: `smtp.gmail.com`
- port: `587` or `465` (587 for tls, 465 for ssl)
- protocol: `tls` or `ssl`
- user: `YOUR_USERNAME@gmail.com`
- password: `YOUR_PASSWORD`

2. The given Gmail account settings:
 - If you've turned on 2-Step Verification for your account, you might need to enter an [App password][1].
 - Without 2-Step Verification:
   1. Allow [less secure apps access][2] to your account.
   2. Visit http://www.google.com/accounts/DisplayUnlockCaptcha and sign in with your Gmail username and password.


  [1]: https://support.google.com/accounts/answer/185834?hl=en#ASPs
  [2]: https://support.google.com/accounts/answer/6010255
