### ISSUE TITLE
Unresolved dependency error for 5.0 plugin while migrating existing play project from 2.4.x to 2.5.10 

### ISSUE THREAD

**Issue by bhavyalatha26** [playframework/play-mailer#117]
Operating System : Windows 10

I have an existing play project running on 2.4.x , and we plan to migrate to 2.5.x .With the help of play migration guide for 2.5.x , I migrated the project to 2.5.10 and updated the play-mailer plugin from **3.0.1 to 5.0.0**   
"com.typesafe.play" %% "play-mailer" % "5.0.0"   

On clean and compile , I got this error below

```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.sun.mail#javax.mail;1.5.2: several problems occurred while resolving dependency: com.sun.mail#javax.mail;1.5.2 {compile=[compile(*), master(compile)], runtime=[runtime(*)]}:
[warn]  several problems occurred while resolving dependency: com.sun.mail#all;1.5.2 {}:
[warn]  URI has an authority component
[warn]  URI has an authority component
[warn]
[warn]  URI has an authority component
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          com.sun.mail:javax.mail:1.5.2
[warn]            +- org.apache.commons:commons-email:1.4
[warn]            +- com.typesafe.play:play-mailer_2.11:5.0.0 (build.sbt#L25-44)
[warn]            +- <projname>:<projname>_2.11:1.0
sbt.ResolveException: unresolved dependency: com.sun.mail#javax.mail;1.5.2: several problems occurred while resolving dependency: com.sun.mail#javax.mail;1.5.2 {compile=[compile(*), master(compile)], runtime=[runtime(*)]}:
        several problems occurred while resolving dependency: com.sun.mail#all;1.5.2 {}:
        URI has an authority component
        URI has an authority component

        URI has an authority component

        at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
        at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
        at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
        at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
        at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
        at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
        at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
        at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
        at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
        at xsbt.boot.Using$.withResource(Using.scala:10)
        at xsbt.boot.Using$.apply(Using.scala:9)
        at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
        at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
        at xsbt.boot.Locks$.apply0(Locks.scala:31)
        at xsbt.boot.Locks$.apply(Locks.scala:28)
        at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
        at sbt.IvySbt.withIvy(Ivy.scala:128)
        at sbt.IvySbt.withIvy(Ivy.scala:125)
        at sbt.IvySbt$Module.withModule(Ivy.scala:156)
        at sbt.IvyActions$.updateEither(IvyActions.scala:168)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1439)
        at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1435)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1470)
        at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1468)
        at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1473)
        at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1467)
        at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
        at sbt.Classpaths$.cachedUpdate(Defaults.scala:1490)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1417)
        at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1369)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: com.sun.mail#javax.mail;1.5.2: several problems occurred while resolving dependency: com.sun.mail#javax.mail;1.5.2 {compile=[compile(*), master(compile)], runtime=[runtime(*)]}:
[error]         several problems occurred while resolving dependency: com.sun.mail#all;1.5.2 {}:
[error]         URI has an authority component
[error]         URI has an authority component
[error]
[error]         URI has an authority component
```

**NOTE : I was unable to reproduce this error with a new play project - 2.5.10**
 
Do I need to perform any additional migration steps that are not mentioned in the play's official documentation ?

**Comment by Mogztter** [comment]
`URI has an authority component` messages are weird.
 Could you please give me the path of your project and the full `build.sbt` file ?

**Comment by bhavyalatha26** [comment]
hi @Mogztter , this is our build file
```
name := "<app-name>"

version := "1.0"

lazy val root = (project in file(".")).enablePlugins(PlayScala)
  .disablePlugins(PlayLogback)

scalaVersion := "2.11.7"

resolvers += Resolver.sonatypeRepo("releases")

resolvers += Resolver.sonatypeRepo("snapshots")

resolvers += Resolver.bintrayRepo("scalaz","releases")

resolvers += "Yantranet S3 Repository - Snapshots" at "http://ynt-mvn-repo.s3-website-us-east-1.amazonaws.com/snapshot/"

// If you need to add from any of your local maven repository use below configuration
resolvers += "Local Maven Repository" at "file://"+Path.userHome.absolutePath+"/.m2/repository"

doc in Compile <<= target.map(_ / "none")

libraryDependencies ++= Seq(
  cache,
  ws,
  filters,
  "joda-time" % "joda-time" % "2.9.9",
  "org.joda" % "joda-convert" % "1.8.1",
  "com.github.tototoshi" %% "slick-joda-mapper" % "2.2.0",
  "mysql" % "mysql-connector-java" % "5.1.24",
  "com.amazonaws" % "aws-java-sdk" % "1.9.13",
  "com.typesafe.play" %% "play-slick" %"2.0.0",
  "com.typesafe.play" %% "play-slick-evolutions" %"2.0.0",
  "com.typesafe.play" %% "play-mailer" % "3.0.1",
  "c3p0" % "c3p0" % "0.9.1.2",
  "com.google.protobuf" % "protobuf-java" % "2.6.1",
  "org.reactivemongo" %% "play2-reactivemongo" % "0.11.14",
  "com.pubnub" % "pubnub" % "3.7.5"
)

libraryDependencies += specs2 % Test

// speeding up compilation by disabling documentation generation
sources in (Compile , doc) := Seq.empty
publishArtifact in (Compile,packageDoc) := false

javaOptions in Test += "-Dconfig.resource=test.conf"

testOptions in Test := Nil

```

**Comment by joshkamau** [comment]
I had the same issue. I had to change the dependency to this: 
`libraryDependencies += "com.typesafe.play" % "play-mailer_2.11" % "5.0.0"
`
which i found here [https://mvnrepository.com/artifact/com.typesafe.play/play-mailer_2.11/5.0.0](https://mvnrepository.com/artifact/com.typesafe.play/play-mailer_2.11/5.0.0)

**Comment by Mogztter** [comment]
Thanks @joshkamau for the tip.

@bhavyalatha26 Does it solve your issue ? Can we close this issue ?

**Comment by bhavyalatha26** [comment]
yes @mogztter. It solved my issue , thank you @joshkamau
