### ISSUE TITLE
Unable to disable TLS v1.0 with play-mailer 5.0 (using Play 2.5.x)

### ISSUE THREAD

**Issue by nkmittal** [playframework/play-mailer#150]
I disabled TLS version on my Play web server (2.5.x + Scala) using java.security (using Java 8) file as below:
```
jdk.tls.disabledAlgorithms=SSLv3, TLSv1, RC4, MD5withRSA, DH keySize < 768, \
    EC keySize < 224, 3DES_EDE_CBC
```
With this change (TLSv1) I am not able to send emails to smtp.gmail.com:465. I am using play-mailer version 5.0.0. The settings in application.conf file:
```
host = smtp.gmail.com
port = 465
ssl = yes
```
I get following error:
```
Caused by: javax.mail.MessagingException: Could not connect to SMTP host: smtp.gmail.com, port: 465
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2055)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:697)
	at javax.mail.Service.connect(Service.java:386)
	at javax.mail.Service.connect(Service.java:245)
	at javax.mail.Service.connect(Service.java:194)
	at javax.mail.Transport.send0(Transport.java:253)
	at javax.mail.Transport.send(Transport.java:124)
	at org.apache.commons.mail.Email.sendMimeMessage(Email.java:1411)
	at org.apache.commons.mail.Email.send(Email.java:1448)
	at play.api.libs.mailer.SMTPMailer$$anon$2.send(MailerPlugin.scala:100)
Caused by: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
	at sun.security.ssl.Handshaker.activate(Handshaker.java:503)
	at sun.security.ssl.SSLSocketImpl.kickstartHandshake(SSLSocketImpl.java:1482)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1351)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
	at com.sun.mail.util.SocketFetcher.configureSSLSocket(SocketFetcher.java:543)
	at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:348)
	at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:215)
	at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2019)
	at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:697)
```

**Comment by Mogztter** [comment]
That weird, I would expect the handshake to choose TLS v1.1 or v1.2.
Maybe it's mandatory to define `mail.smtp.ssl.protocols=TLSv1.2` ?

**Comment by nkmittal** [comment]
I tried with "mail.smtp.ssl.protocols=TLSv1.2" but it didn't work. I think play-mailer is using only TLSv1.0.

**Comment by Mogztter** [comment]
> I tried with "mail.smtp.ssl.protocols=TLSv1.2"

Where/how did you configure this parameter ?

> I think play-mailer is using only TLSv1.0.

I'm not sure about that. Play mailer is using Java mail to connect and perform the SSL handshake to the mail server.
First we should try to reproduce this issue using only Java mail.

**Comment by nkmittal** [comment]
I added this configuration in application.conf file:
```
play.mailer {
  props {
  mail.smtp.ssl.protocols=TLSv1.2
  }
}
```

**Comment by Mogztter** [comment]
This configuration is only available on master (merged 17 hours ago). If you want to test with this parameter you will need to build this library from the source or wait the next release.

**Comment by nkmittal** [comment]
> This configuration is only available on master (merged 17 hours ago). If you want to test with this parameter you will need to build this library from the source or wait the next release.

Should I assume that play-mailer 5.0 will not work when TLSv1.0 is disabled in java.security ? This is going to be a problem as I have lot of dependency on play-mailer on sending emails. I don't want to upgrade to Play 2.6.x at this time as my web application is in production.

**Comment by Mogztter** [comment]
> Should I assume that play-mailer 5.0 will not work when TLSv1.0 is disabled in java.security ?

First I need to reproduce this issue with Java mail and Play mailer. Maybe a workaround exists and if it's not the case we could backport this new feature to Play mailer 5.x (compatible with Play 2.5.x).

> I don't want to upgrade to Play 2.6.x at this time as my web application is in production.

I understand, don't worry we will find a solution :wink:

**Comment by Mogztter** [comment]
I'm reading this issue again: https://github.com/playframework/play-mailer/issues/134

I think your configuration should be:
```
host = smtp.gmail.com
port = 587
tls = yes
tlsRequired = yes
```
Since you want to use TLS (not SSL). And as mentioned in https://github.com/playframework/play-mailer/issues/134 you should define system properties: 

```java
System.setProperty("mail.transport.protocol", "smtps"); // not sure about this one for Gmail
System.setProperty("mail.smtps.ssl.protocols", "TLSv1.2");
```

**Comment by nkmittal** [comment]
> I'm reading this issue again: #134
> 
> I think your configuration should be:
> 
> ```
> host = smtp.gmail.com
> port = 587
> tls = yes
> tlsRequired = yes
> ```
> 
> Since you want to use TLS (not SSL). And as mentioned in #134 you should define system properties:
> 
> ```java
> System.setProperty("mail.transport.protocol", "smtps"); // not sure about this one for Gmail
> System.setProperty("mail.smtps.ssl.protocols", "TLSv1.2");
> ```

I tried that config (in Play config file)  but it didn't work. But I didn't try the System properties. I will try that and update.

**Comment by nkmittal** [comment]
Ok it works. Just need to pass one System property when running Play web app:
`-Dmail.smtp.ssl.protocols=TLSv1.2`

NOTE: Need 'smtp' only. No need for 'smtps'. 
Thanks a lot for the help !

**Comment by mkurz** [comment]
Great! I the next version it should be possible to just configure the setting like you already described in [your command above](https://github.com/playframework/play-mailer/issues/150#issuecomment-422325756).

**Comment by Mogztter** [comment]
> Thanks a lot for the help !

You're welcome 👍
